<a href="https://colab.research.google.com/github/ssubratkumar106-blip/Practice-15-08-25/blob/main/Copy_of_Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
def sigmoid(x):
  return 1/(1+math.exp(-x))

In [ ]:
sigmoid(100)

1.0

In [ ]:
sigmoid(1)

0.7310585786300049

In [ ]:
sigmoid(-2)

0.11920292202211755

In [ ]:
def tanh(x):
  return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [ ]:
tanh(-56)

-1.0

In [ ]:
tanh(50)

1.0

In [ ]:
def relu(x):
  return max(0,x)

In [ ]:
relu(-7)

0

In [ ]:
relu(6)

6

6

In [ ]:
def leaky_relu(x):
  return max(0.1*x,x)

In [ ]:
leaky_relu(-100)

-10.0

In [ ]:
leaky_relu(8)

8

import numpy as np

In [ ]:
import numpy as np

In [ ]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [ ]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [ ]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [ ]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [ ]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mae(y_true,y_predicted):
  total_error = 0
  for yt,yp in zip(y_true, y_predicted):
    print(yt,yp)

In [ ]:
mae(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [ ]:
def mae(y_true,y_predicted):
  total_error = 0
  for yt,yp in zip(y_true, y_predicted):
    total_error += abs(yt-yp)
    print(total_error)
    mae = total_error/len(y_true)
    print(mae)
    return mae

In [ ]:
mae(y_true,y_predicted)

0.7
0.13999999999999999


np.float64(0.13999999999999999)

In [ ]:
np.mean(np.abs(y_predicted - y_true))

np.float64(0.5)

In [ ]:
np.log([0.000000000000000000000000000000000000000000000000000000001])

array([-131.2473503])

In [ ]:
epsilon = 1e-15

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [ ]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new


[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
np.log(y_predicted)

/tmp/ipython-input-815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [ ]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [ ]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15

    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [ ]:
log_loss(y_true,y_predicted)

np.float64(17.2696280766844)